# Generated by Django 3.0.14 on 2022-03-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Khawadawa',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('person_will_feed', models.CharField(blank=True, max_length=100, null=True)),
                ('program_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'KhawaDawa',
                'managed': False,
            },
        ),
    ]
